// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFV8RPl38P6CTmJJ8tLq6fq6quIGVH3nM',
    appId: '1:471973895070:web:8fa93ff4cfe9805f84548f',
    messagingSenderId: '471973895070',
    projectId: 'technostrelka-2025',
    authDomain: 'technostrelka-2025.firebaseapp.com',
    storageBucket: 'technostrelka-2025.firebasestorage.app',
    measurementId: 'G-DFY1RCM88M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAInlzuuPAfNeVGyojk1Qle6qb2IyFSNeM',
    appId: '1:471973895070:android:b91c7f7ee6f750a584548f',
    messagingSenderId: '471973895070',
    projectId: 'technostrelka-2025',
    storageBucket: 'technostrelka-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxuQacz_4hlCe_wKUdT3dNiMguTlrJ2Y',
    appId: '1:471973895070:ios:b024007f95bdb75284548f',
    messagingSenderId: '471973895070',
    projectId: 'technostrelka-2025',
    storageBucket: 'technostrelka-2025.firebasestorage.app',
    iosBundleId: 'com.example.technostrelka2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxuQacz_4hlCe_wKUdT3dNiMguTlrJ2Y',
    appId: '1:471973895070:ios:b024007f95bdb75284548f',
    messagingSenderId: '471973895070',
    projectId: 'technostrelka-2025',
    storageBucket: 'technostrelka-2025.firebasestorage.app',
    iosBundleId: 'com.example.technostrelka2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFV8RPl38P6CTmJJ8tLq6fq6quIGVH3nM',
    appId: '1:471973895070:web:a12d0a81218a0a7484548f',
    messagingSenderId: '471973895070',
    projectId: 'technostrelka-2025',
    authDomain: 'technostrelka-2025.firebaseapp.com',
    storageBucket: 'technostrelka-2025.firebasestorage.app',
    measurementId: 'G-XMW4QK1XGM',
  );
}
